name: Build wheels

on:
  push:
    branches:
      - master

jobs:
  # Build wheels for macOS, Linux, and Windows
  build_wheels:
    name: Wheel for ${{ matrix.os }}-cp${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: [36, 37, 38, 39]

    steps:
      # - name: Install boost
      #   uses: MarkusJx/install-boost@v2.0.0
      #   id: install-boost
      #   with:
      #     boost_version: 1.71.0
      #   if: runner.os == 'Windows'

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: conda-env
        if: runner.os == 'Windows' || runner.os == 'Linux'

      - name: Install libraries for Windows
        run: |
          conda install -c conda-forge boost
          conda install -c conda-forge eigen
        shell: pwsh
        if: runner.os == 'Windows'

      - name: Install libraries for Linux
        run: |
          conda install -c conda-forge boost
          conda install -c conda-forge eigen
          # sudo apt-get update
          # sudo apt-get install libboost-all-dev
        shell: bash
        if: runner.os == 'Linux'

      - name: Install libraries for macOS
        run: |
          brew upgrade
          brew install boost
          brew install eigen
        shell: bash
        if: runner.os == 'macOS'

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheel
        run:
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*

      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
